#!/usr/bin/env python3
"""Generate a production env file for the BankingApp API."""

from __future__ import annotations

import argparse
import base64
import secrets
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
APP_ROOT = SCRIPT_DIR.parents[1]
API_PROJECT = APP_ROOT / "src" / "BankingApp.Api"
DEFAULT_OUTPUT = API_PROJECT / ".env.production.generated"

JWT_SECRET_BYTES = 48
OTP_SECRET_BYTES = 32
PLACEHOLDER_SMTP_HOST = "smtp.example.com"
PLACEHOLDER_SMTP_USER = "noreply@example.com"
PLACEHOLDER_SMTP_PASS = "replace-me"


def generate_base64_secret(byte_count: int) -> str:
    """Generate a base64-encoded random secret."""
    return base64.b64encode(secrets.token_bytes(byte_count)).decode("ascii")


def write_env_file(path: Path, values: dict[str, str]) -> None:
    """Write production env values."""
    lines = [
        "# Generated by scripts/secrets/generate_prod_env.py.",
        "# Install these values into the production secret store. Do not commit this file.",
        "",
    ]
    lines.extend(f"{key}={value}" for key, value in values.items())
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description="Generate a production env file for BankingApp.Api.")
    parser.add_argument(
        "--connection-string",
        required=True,
        help="Production SQL Server connection string.",
    )
    parser.add_argument("--smtp-host", default=None, help="SMTP host.")
    parser.add_argument("--smtp-port", default="587", help="SMTP port.")
    parser.add_argument("--smtp-user", default=None, help="SMTP username.")
    parser.add_argument("--smtp-pass", default=None, help="SMTP password.")
    parser.add_argument("--smtp-from", default=None, help="SMTP sender address.")
    parser.add_argument(
        "--allow-placeholder-smtp",
        action="store_true",
        help="Allow placeholder SMTP values in the generated production env file.",
    )
    parser.add_argument(
        "--apply-migrations",
        action="store_true",
        help="Set Database__ApplyMigrations=true. Default is false for production.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output env file. Defaults to {DEFAULT_OUTPUT}.",
    )
    parser.add_argument("--force", action="store_true", help="Overwrite an existing output file.")
    return parser.parse_args()


def main() -> None:
    """Generate production configuration."""
    args = parse_args()
    output = args.output.resolve()

    if output.exists() and not args.force:
        raise SystemExit(f"{output} already exists. Re-run with --force to overwrite it.")

    smtp_missing = not args.smtp_host or not args.smtp_user or not args.smtp_pass
    if smtp_missing and not args.allow_placeholder_smtp:
        raise SystemExit(
            "Production SMTP values are incomplete. Provide --smtp-host, --smtp-user, and --smtp-pass, "
            "or pass --allow-placeholder-smtp deliberately."
        )

    smtp_host = args.smtp_host or PLACEHOLDER_SMTP_HOST
    smtp_user = args.smtp_user or PLACEHOLDER_SMTP_USER
    smtp_pass = args.smtp_pass or PLACEHOLDER_SMTP_PASS
    smtp_from = args.smtp_from or smtp_user

    values = {
        "ASPNETCORE_ENVIRONMENT": "Production",
        "ConnectionStrings__BankingAppDb": args.connection_string,
        "Jwt__Secret": generate_base64_secret(JWT_SECRET_BYTES),
        "Otp__Secret": generate_base64_secret(OTP_SECRET_BYTES),
        "Email__SmtpHost": smtp_host,
        "Email__SmtpPort": args.smtp_port,
        "Email__SmtpUser": smtp_user,
        "Email__SmtpPass": smtp_pass,
        "Email__FromAddress": smtp_from,
        "Database__ApplyMigrations": "true" if args.apply_migrations else "false",
    }

    output.parent.mkdir(parents=True, exist_ok=True)
    write_env_file(output, values)

    print("Generated production env file:")
    print(f"  {output}")
    print("\nInstall these values into the server, Docker, CI/CD, or hosting secret store.")
    print("Do not commit the generated file.")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(130)
