// <copyright file="TwoFactorMethod.cs" company="CtrlC CtrlV">
// Copyright (c) CtrlC CtrlV. All rights reserved.
// </copyright>
// <summary>
// Contains the TwoFactorMethod values.
// </summary>

namespace BankApp.Application.Enums;

/// <summary>
///     Defines the application-facing two-factor delivery methods exposed to presentation clients.
/// </summary>
public enum TwoFactorMethod
{
    /// <summary>
    ///     The code is delivered by email.
    /// </summary>
    Email = 0,

    /// <summary>
    ///     The code is delivered by phone.
    /// </summary>
    Phone = 1,

    /// <summary>
    ///     The code is generated by an authenticator app.
    /// </summary>
    Authenticator = 2,
}
