// <copyright file="TwoFactorMethod.cs" company="CtrlC CtrlV">
// Copyright (c) CtrlC CtrlV. All rights reserved.
// </copyright>
// <summary>
// Contains the TwoFactorMethod values.
// </summary>

namespace BankApp.Domain.Enums;

/// <summary>
///     Represents the delivery channel used for 2FA.
/// </summary>
public enum TwoFactorMethod
{
    /// <summary>
    ///     The OTP is delivered to the user's registered email address.
    /// </summary>
    Email,

    /// <summary>
    ///     The OTP is generated by a TOTP authenticator application (e.g. Google Authenticator).
    /// </summary>
    Authenticator,

    /// <summary>
    ///     The OTP is delivered via SMS to the user's registered phone number.
    /// </summary>
    Phone,
}