<Project>
    <PropertyGroup>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest-recommended</AnalysisLevel>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <WarningsNotAsErrors>$(WarningsNotAsErrors);IDE0007;IDE0008;IDE0062;CA1822;CA1848</WarningsNotAsErrors>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Roslynator.Analyzers" Version="4.15.0" PrivateAssets="all"/>
    </ItemGroup>
</Project>
