<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <UserSecretsId>6321c0d0-8c18-47df-b537-61e283ac2339</UserSecretsId>
        <RootNamespace>BankingApp.Api</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="ErrorOr" Version="2.1.0"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Serilog.AspNetCore" Version="8.0.3"/>
        <PackageReference Include="Serilog.Sinks.File" Version="6.0.0"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\BankingApp.Application\BankingApp.Application.csproj"/>
        <ProjectReference Include="..\BankingApp.Infrastructure\BankingApp.Infrastructure.csproj"/>
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Common\Mappers\" />
      <Folder Include="DependencyInjection\" />
      <Folder Include="_Features\AccountOverview\" />
      <Folder Include="_Features\Authentication\" />
      <Folder Include="_Features\Beneficiaries\" />
      <Folder Include="_Features\Billers\" />
      <Folder Include="_Features\BillPayments\" />
      <Folder Include="_Features\ForexRateAlerts\" />
      <Folder Include="_Features\Forex\" />
      <Folder Include="_Features\PasswordReset\" />
      <Folder Include="_Features\RecurringPayments\" />
      <Folder Include="_Features\Transfers\" />
      <Folder Include="_Features\UserProfile\" />
      <Folder Include="_Features\UserRegistration\" />
    </ItemGroup>
</Project>
